title: ShisaQ
description: My Personal GitHub Blog
author: ShisaQ
logo: /static/img/avatar.jpg
github: https://github.com/shisaq
about: Front-end Developer

baseurl: "https://shisaq.com"
url: "https://shisaq.com"
enforce_ssl: "https://shisaq.com"

disqus_shortname: shisaq
google_analytics: UA-73217350-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
